INSERT INTO FII (id,name,type) VALUES  (1,'ABCP11','SHOPPING');
INSERT INTO FII (id,name,type) VALUES  (2,'GGRC11','LOGISTIC');
INSERT INTO FII (id,name,type) VALUES  (3,'HGLG11','LOGISTIC');
INSERT INTO FII (id,name,type) VALUES  (4,'HGRE11','COORPORATE');
INSERT INTO FII (id,name,type) VALUES  (5,'MXRF11','PAPER');
INSERT INTO FII (id,name,type) VALUES  (6,'FLMA11','COORPORATE');
INSERT INTO FII (id,name,type) VALUES  (7,'EDGA11','HIBRID');
INSERT INTO FII (id,name,type) VALUES  (8,'CTXT11','COORPORATE');
INSERT INTO FII (id,name,type) VALUES  (9,'SDIL11','LOGISTIC');
INSERT INTO FII (id,name,type) VALUES  (10,'KNRI11','HIBRID');
INSERT INTO FII (id,name,type) VALUES  (11,'CBOP11','COORPORATE');
INSERT INTO FII (id,name,type) VALUES  (12,'HGBS11','SHOPPING');
INSERT INTO FII (id,name,type) VALUES  (13,'AGCX11','BANK_AGENCY');


INSERT INTO PERSON VALUES(1,'gabrielcastilho.cardelli@gmail.com','Gabriel Cardelli','123456');
